2013-05-29 20:45:19.258239:
Traceback (most recent call last):

  File "/home/age/Scripts/BitCoins/Encrypted/Libraries/BitCoinInterface.py", line 33, in LoadConfig

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 1: invalid start byte


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "./Trader.py", line 141, in <module>
    BTCInstance = BitCoinInterface([HomeCurrency, TradeCurrency, MultiMarketPrediction, Hash])

  File "/home/age/Scripts/BitCoins/Encrypted/Libraries/BitCoinInterface.py", line 87, in __init__

  File "/home/age/Scripts/BitCoins/Encrypted/Libraries/BitCoinInterface.py", line 36, in LoadConfig

Exception: Incorrect Security Key

2013-05-29 20:46:46.291332:
Traceback (most recent call last):

  File "/home/age/Scripts/BitCoins/Encrypted/Libraries/BitCoinInterface.py", line 33, in LoadConfig

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 1: invalid start byte


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "Trader.py", line 141, in <module>
    BTCInstance = BitCoinInterface([HomeCurrency, TradeCurrency, MultiMarketPrediction, Hash])

  File "/home/age/Scripts/BitCoins/Encrypted/Libraries/BitCoinInterface.py", line 87, in __init__

  File "/home/age/Scripts/BitCoins/Encrypted/Libraries/BitCoinInterface.py", line 36, in LoadConfig

Exception: Incorrect Security Key

